from .setup import *


BOTTOM_PANEL_COLOR = BROWN

# ######## Utility
SAVE_BUTTON_X_OFFSET = 15
SAVE_BUTTON_Y_OFFSET = 15 + SCREEN_HEIGHT

LOAD_BUTTON_X_OFFSET = 15
LOAD_BUTTON_Y_OFFSET = 60 + SCREEN_HEIGHT

NAME_BUTTON_X_OFFSET = 15
NAME_BUTTON_Y_OFFSET = 105 + SCREEN_HEIGHT

BACK_BUTTON_X_OFFSET_NAME_SCREEN = (SCREEN_WIDTH + RIGHT_MARGIN) // 2 - 32
BACK_BUTTON_Y_OFFSET_NAME_SCREEN = SCREEN_HEIGHT + BOTTOM_MARGIN - 50
