from .setup import *


GRID_LINE_COLOR = WHITE

# ######## Saved maps
SAVED_MAPS_X_OFFSET = (SCREEN_WIDTH + RIGHT_MARGIN) // 3
SAVED_MAPS_Y_OFFSET = 100
SAVED_MAPS_Y_SPACING = 75

SAVED_MAPS_HIGHLIGHT_WIDTH = 10
SAVED_MAPS_COLOR = (255, 255, 255)
SAVED_MAPS_HIGHLIGHT_COLOR = (200, 25, 25)


# ######## Change Name
CHANGE_NAME_TITLE_Y_OFFSET = 300

CHANGE_NAME_X_OFFSET = None
CHANGE_NAME_Y_OFFSET = 550

CHANGE_NAME_TITLE_COLOR = (255, 255, 255)
CHANGE_NAME_COLOR = (255, 255, 255)

