from settings.setup import *


# Saved maps
SAVED_MAPS_X = (SCREEN_WIDTH + RIGHT_MARGIN) // 3
SAVED_MAPS_Y = 100
SAVED_MAPS_Y_SPACING = 75

SAVED_MAPS_HIGHLIGHT_WIDTH = 5
SAVED_MAPS_COLOR = WHITE
SAVED_MAPS_HIGHLIGHT_COLOR = RED


# Change name
CHANGE_NAME_TITLE_Y = 300

CHANGE_NAME_X = None
CHANGE_NAME_Y = 550

CHANGE_NAME_TITLE_COLOR = WHITE
CHANGE_NAME_COLOR = WHITE


# Preferences
PREFERENCES_X = (SCREEN_WIDTH + RIGHT_MARGIN) // 3
PREFERENCES_Y = 200
PREFERENCES_Y_SPACING = 100

SELECTED_PREFERENCE_KEY_Y = 600
SELECTED_PREFERENCE_VAL_Y = 700

PREFERENCES_HIGHLIGHT_WIDTH = 10

PREFERENCES_COLOR = WHITE
PREFERENCES_HIGHLIGHT_COLOR = RED
