from .setup import *


MINIMAP_WIDTH = BOTTOM_MARGIN
MINIMAP_HEIGHT = BOTTOM_MARGIN
MINIMAP_OUTLINE_WIDTH = 3
MINIMAP_PANEL_COLOR = BROWN
MINIMAP_OUTLINE_COLOR = ORANGE

MAP_OUTLINE_WIDTH = 1
MAP_OUTLINE_COLOR = WHITE

MAP_VIEW_OUTLINE_WIDTH = 3
MAP_VIEW_OUTLINE_COLOR = GREEN
