from settings.setup import *


RIGHT_PANEL_COLOR = BROWN
BOTTOM_PANEL_COLOR = BROWN


# ######## Presets ######## #
PRESETS_MAX_NAME_LENGTH = 15
PRESETS_NAME_FONT_HEIGHT = 32  # linked with fonts.py
PRESETS_NAME_X_OFFSET = SCREEN_WIDTH + 20
PRESETS_NAME_Y_OFFSET = 75
PRESETS_NAME_Y_SPACING = PRESETS_NAME_FONT_HEIGHT * 1.5
PRESETS_HIGHLIGHT_WIDTH = 3
PRESETS_HIGHLIGHT_LEFT_OFFSET = -5
PRESETS_HIGHLIGHT_RIGHT_OFFSET = 10
PRESETS_HIGHLIGHT_TOP_OFFSET = - PRESETS_HIGHLIGHT_WIDTH * 2
PRESETS_HIGHLIGHT_BOTTOM_OFFSET = PRESETS_HIGHLIGHT_WIDTH * 2

PRESETS_NAME_COLOR = (255, 255, 255)
PRESETS_HIGHLIGHT_COLOR = (200, 25, 25)

MAX_NR_PRESETS = 15


# ######## Tile Preview ######## #
PREVIEW_X = SCREEN_WIDTH + RIGHT_MARGIN - 64
PREVIEW_Y = 70
PREVIEW_WIDTH = 32
PREVIEW_HEIGHT = 32


# ######## Tiles ######## #
TILE_SIZE_X = 32
TILE_SIZE_Y = 32

TILE_HIGHLIGHT_COLOR = (200, 25, 25)
TILE_LABEL_COLOR = (255, 255, 255)

TILE_X = 35
TILE_X_SPACING = 85
TILE_START_Y = 100
TILE_Y_OFFSET = 80
TILE_LABEL_Y_OFFSET = 20
TILE_HIGHLIGHT_WIDTH = 3
TILE_HIGHLIGHT_LEFT_OFFSET = -3
TILE_HIGHLIGHT_RIGHT_OFFSET = 6

MAX_NR_TILES = 27
MAX_TILE_NAME_LENGTH = 7
